---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudbeat
subjects:
  - kind: ServiceAccount
    name: cloudbeat
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudbeat-role-binding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: cloudbeat
    namespace: kube-system
roleRef:
  kind: Role
  name: cloudbeat-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudbeat-kubeadm-config
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: cloudbeat
    namespace: kube-system
roleRef:
  kind: Role
  name: cloudbeat-kubeadm-config
  apiGroup: rbac.authorization.k8s.io