---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudbeat-role
  # should be the namespace where cloudbeat is running
  namespace: kube-system
  labels:
    k8s-app: cloudbeat
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudbeat-kubeadm-config
  namespace: kube-system
  labels:
    k8s-app: cloudbeat
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - kubeadm-config
    verbs: ["get"]