// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.15.0. DO NOT EDIT.

package cloudwatch

import (
	context "context"

	types "github.com/aws/aws-sdk-go-v2/service/cloudwatch/types"
	mock "github.com/stretchr/testify/mock"
)

// MockCloudwatch is an autogenerated mock type for the Cloudwatch type
type MockCloudwatch struct {
	mock.Mock
}

// DescribeAlarms provides a mock function with given fields: ctx, filters
func (_m *MockCloudwatch) DescribeAlarms(ctx context.Context, filters []string) ([]types.MetricAlarm, error) {
	ret := _m.Called(ctx, filters)

	var r0 []types.MetricAlarm
	if rf, ok := ret.Get(0).(func(context.Context, []string) []types.MetricAlarm); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.MetricAlarm)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockCloudwatch interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCloudwatch creates a new instance of MockCloudwatch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCloudwatch(t mockConstructorTestingTNewMockCloudwatch) *MockCloudwatch {
	mock := &MockCloudwatch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
