# $COMMUNITY/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../../base

patches:
  - path: ./patches/patch-add-ssl-certs.yaml
    target:
      kind: DaemonSet

secretGenerator:
  - behavior: create
    name: elastic-package-certs
    files:
      - ./ca-cert.pem

configMapGenerator:
  - name: cloudbeat-daemonset-config
    behavior: create
    files:
      - cloudbeat.yml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    k8s-app: cloudbeat
