# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
run:
  timeout: 10m

linters:
  enable:
    - contextcheck
    - exhaustruct
    - gocyclo
    - reassign
    - misspell
    - nolintlint
    - unconvert
    - unparam
    - whitespace
# TODO: These are good but need some work to fix everything
#    - gocritic
#    - revive

linters-settings:
  govet:
    settings:
      printf:
        funcs:
          - Infof
          - Debugf
          - Warnf
          - Errorf
          - Fatalf
          - Panicf
          - DPanicf
  exhaustruct:
    # List of regular expressions to match struct packages and names.
    # If this list is empty, all structs are tested.
    # Default: []
    include:
      - '.*cloudbeat.*fetching.ResourceInfo'
      - '.*cloudbeat.*fetching.fetchers.*'
    exclude:
      - '.*cloudbeat.*fetching.fetchers.k8s.FileCommonData'
      - '.*cloudbeat.*fetching.fetchers.k8s.ProcCommonData'
