# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
run:
  timeout: 15m

linters:
  enable:
    - containedctx
    - contextcheck
    - exhaustruct
    - exportloopref
    - gci
    - gocritic
    - gocyclo
    - gofmt
    - misspell
    - nolintlint
    - reassign
    - testifylint
    - unconvert
    - unparam
    - whitespace
# TODO: These are good but need some work to fix everything
#    - revive

linters-settings:
  gocritic:
    settings:
      ifElseChain:
        minThreshold: 3
  gci:
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # The default order of sections is `standard > default > custom > blank > dot`,
    # If `custom-order` is `true`, it follows the order of `sections` option.
    # Default: ["standard", "default"]
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/elastic/cloudbeat) # Custom section: groups all imports with the specified Prefix.
    skip-generated: true
    # Enable custom order of sections.
    # If `true`, make the section order the same as the order of `sections`.
    custom-order: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      printf:
        funcs:
          - Infof
          - Debugf
          - Warnf
          - Errorf
          - Fatalf
          - Panicf
          - DPanicf
  exhaustruct:
    # List of regular expressions to match struct packages and names.
    # If this list is empty, all structs are tested.
    # Default: []
    include:
      - '.*cloudbeat.*fetching.ResourceInfo'
      - '.*cloudbeat.*fetching.fetchers.*'
      # Check that individual benchmarks always have their dependencies initialized
      - '.*cloudbeat.*flavors.benchmark.*'
      - '.*cloudbeat.*governance.Subscription'
      - '.*cloudbeat.*governance.ManagementGroup'
    exclude:
      - '.*cloudbeat.*fetching.fetchers.k8s.FileCommonData'
      - '.*cloudbeat.*fetching.fetchers.k8s.ProcCommonData'
      - '.*cloudbeat.*fetching.fetchers.*<anonymous>'
      - '.*cloudbeat.*flavors.benchmark.*<anonymous>'
  tenv:
    all: true
