template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/elastic/cloudbeat:
    config:
      all: true
      filename: '{{ .InterfaceFile | base | clean | trimSuffix ".go" }}_mock.go'
      dir: '{{ .InterfaceDir }}'
      exclude-subpkg-regex:
        - vendor
        - deploy/test-environments/.terraform
        - tools
        - scripts
      structname: '{{ .Mock }}{{ .InterfaceName | firstUpper }}'
      recursive: true
