# https://vektra.github.io/mockery/latest/configuration/

packages:
  github.com/elastic/cloudbeat:
    config:
      inpackage: true
      all: true
      with-expecter: true
      recursive: true
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      mockname: "{{ .Mock }}{{ .InterfaceName | firstUpper }}"
      dir: "{{ .InterfaceDir }}"
      outpkg: "{{ .PackageName }}"
      exclude:
        - vendor
        - deploy/test-environments/.terraform
        - tools
