# Todo delete before merge to elastic/beats
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cloudbeat-demo
  name: cloudbeat-demo
spec:
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  containers:
    - image: cloudbeat
      name: cloudbeat-demo
      imagePullPolicy: Always
      volumeMounts:
        - name: proc
          mountPath: /hostfs/proc
          readOnly: true
        - name: cgroup
          mountPath: /hostfs/sys/fs/cgroup
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: etckubernetes
          mountPath: /hostfs/etc/kubernetes
          readOnly: true
        - name: varlib
          mountPath: /hostfs/var/lib
          readOnly: true
        - name: etcsysmd
          mountPath: /hostfs/etc/systemd
          readOnly: true
  volumes:
    - name: proc
      hostPath:
        path: /proc
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
    - name: varlog
      hostPath:
        path: /var/log
    - name: etckubernetes
      hostPath:
        path: /etc/kubernetes
    - name: varlib
      hostPath:
        path: /var/lib
    - name: etcsysmd
      hostPath:
        path: /etc/systemd
  restartPolicy: Always
