// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cloudwatch

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/cloudwatch/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCloudwatch creates a new instance of MockCloudwatch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloudwatch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloudwatch {
	mock := &MockCloudwatch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCloudwatch is an autogenerated mock type for the Cloudwatch type
type MockCloudwatch struct {
	mock.Mock
}

type MockCloudwatch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCloudwatch) EXPECT() *MockCloudwatch_Expecter {
	return &MockCloudwatch_Expecter{mock: &_m.Mock}
}

// DescribeAlarms provides a mock function for the type MockCloudwatch
func (_mock *MockCloudwatch) DescribeAlarms(ctx context.Context, region *string, filters []string) ([]types.MetricAlarm, error) {
	ret := _mock.Called(ctx, region, filters)

	if len(ret) == 0 {
		panic("no return value specified for DescribeAlarms")
	}

	var r0 []types.MetricAlarm
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, []string) ([]types.MetricAlarm, error)); ok {
		return returnFunc(ctx, region, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, []string) []types.MetricAlarm); ok {
		r0 = returnFunc(ctx, region, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.MetricAlarm)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, []string) error); ok {
		r1 = returnFunc(ctx, region, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudwatch_DescribeAlarms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeAlarms'
type MockCloudwatch_DescribeAlarms_Call struct {
	*mock.Call
}

// DescribeAlarms is a helper method to define mock.On call
//   - ctx context.Context
//   - region *string
//   - filters []string
func (_e *MockCloudwatch_Expecter) DescribeAlarms(ctx interface{}, region interface{}, filters interface{}) *MockCloudwatch_DescribeAlarms_Call {
	return &MockCloudwatch_DescribeAlarms_Call{Call: _e.mock.On("DescribeAlarms", ctx, region, filters)}
}

func (_c *MockCloudwatch_DescribeAlarms_Call) Run(run func(ctx context.Context, region *string, filters []string)) *MockCloudwatch_DescribeAlarms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCloudwatch_DescribeAlarms_Call) Return(metricAlarms []types.MetricAlarm, err error) *MockCloudwatch_DescribeAlarms_Call {
	_c.Call.Return(metricAlarms, err)
	return _c
}

func (_c *MockCloudwatch_DescribeAlarms_Call) RunAndReturn(run func(ctx context.Context, region *string, filters []string) ([]types.MetricAlarm, error)) *MockCloudwatch_DescribeAlarms_Call {
	_c.Call.Return(run)
	return _c
}
