// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cloudwatch

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DescribeAlarms provides a mock function for the type MockClient
func (_mock *MockClient) DescribeAlarms(ctx context.Context, params *cloudwatch.DescribeAlarmsInput, optFns ...func(*cloudwatch.Options)) (*cloudwatch.DescribeAlarmsOutput, error) {
	// func(*cloudwatch.Options)
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DescribeAlarms")
	}

	var r0 *cloudwatch.DescribeAlarmsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatch.DescribeAlarmsInput, ...func(*cloudwatch.Options)) (*cloudwatch.DescribeAlarmsOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatch.DescribeAlarmsInput, ...func(*cloudwatch.Options)) *cloudwatch.DescribeAlarmsOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DescribeAlarmsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudwatch.DescribeAlarmsInput, ...func(*cloudwatch.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_DescribeAlarms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeAlarms'
type MockClient_DescribeAlarms_Call struct {
	*mock.Call
}

// DescribeAlarms is a helper method to define mock.On call
//   - ctx context.Context
//   - params *cloudwatch.DescribeAlarmsInput
//   - optFns ...func(*cloudwatch.Options)
func (_e *MockClient_Expecter) DescribeAlarms(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_DescribeAlarms_Call {
	return &MockClient_DescribeAlarms_Call{Call: _e.mock.On("DescribeAlarms",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_DescribeAlarms_Call) Run(run func(ctx context.Context, params *cloudwatch.DescribeAlarmsInput, optFns ...func(*cloudwatch.Options))) *MockClient_DescribeAlarms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudwatch.DescribeAlarmsInput
		if args[1] != nil {
			arg1 = args[1].(*cloudwatch.DescribeAlarmsInput)
		}
		var arg2 []func(*cloudwatch.Options)
		variadicArgs := make([]func(*cloudwatch.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*cloudwatch.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_DescribeAlarms_Call) Return(describeAlarmsOutput *cloudwatch.DescribeAlarmsOutput, err error) *MockClient_DescribeAlarms_Call {
	_c.Call.Return(describeAlarmsOutput, err)
	return _c
}

func (_c *MockClient_DescribeAlarms_Call) RunAndReturn(run func(ctx context.Context, params *cloudwatch.DescribeAlarmsInput, optFns ...func(*cloudwatch.Options)) (*cloudwatch.DescribeAlarmsOutput, error)) *MockClient_DescribeAlarms_Call {
	_c.Call.Return(run)
	return _c
}
