AWSTemplateFormatVersion: "2010-09-09"

Description: Creates elastic-agent cspm user, role, and access key, and outputs the access key

Parameters: {}

Resources:
  ElasticCSPMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join
        - '-'
        - - elasticagent-user-cspm
          - !Select
            - 2
            - !Split
              - /
              - !Ref AWS::StackId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
      Path: /

  ElasticCSPMAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref ElasticCSPMUser

Outputs:
  AccessKeyId:
    Description: Access Key ID
    Value: !Ref ElasticCSPMAccessKey

  SecretAccessKey:
    Description: Secret Access Key
    Value: !GetAtt ElasticCSPMAccessKey.SecretAccessKey
