---
AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an EC2 instance with permissions to run elastic-agent
Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-arm64"
  InstanceType:
    Type: String
    Default: m6g.xlarge
    AllowedValues:
      - m6g.xlarge
      - m6g.2xlarge
      - m6g.4xlarge
    Description: The type of EC2 instance to create
  EnrollmentToken:
    Type: String
    Description: The enrollment token of elastic-agent
  FleetUrl:
    Type: String
    Description: The fleet URL of elastic-agent
  ElasticArtifactServer:
    Type: String
    Description: The URL of the artifact server
    Default: https://artifacts.elastic.co/downloads/beats/elastic-agent
  ElasticAgentVersion:
    Type: String
    Description: The version of elastic-agent to install
Resources:
  # Security Group for EC2 instance
  ElasticAgentSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName:
        Fn::Join:
          - "-"
          - - "elastic-agent-security-group"
            - Fn::Select:
                - 2
                - Fn::Split:
                    - "/"
                    - Ref: "AWS::StackId"
      GroupDescription: Block incoming traffic
      SecurityGroupIngress: []
  # IAM Role for EC2 instance
  ElasticAgentRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
  # Instance profile to attach to EC2 instance
  ElasticAgentInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName:
        Fn::Join:
          - "-"
          - - "elastic-agent-instance-profile"
            - Fn::Select:
                - 2
                - Fn::Split:
                    - "/"
                    - Ref: "AWS::StackId"
      Path: /
      Roles:
        - Ref: "ElasticAgentRole"
  # EC2 Instance to run elastic-agent
  ElasticAgentEc2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - "-"
              - - "elastic-agent-instance"
                - Fn::Select:
                    - 2
                    - Fn::Split:
                        - "/"
                        - Ref: "AWS::StackId"
        - Key: Task
          Value: Cloud Security Posture Management Scanner
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref ElasticAgentInstanceProfile
      SecurityGroupIds:
        - !Ref ElasticAgentSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          ElasticAgentArtifact=elastic-agent-${ElasticAgentVersion}-linux-arm64
          curl -L -O ${ElasticArtifactServer}/$ElasticAgentArtifact.tar.gz
          tar xzvf $ElasticAgentArtifact.tar.gz
          cd $ElasticAgentArtifact
          sudo ./elastic-agent install --non-interactive --url=${FleetUrl} --enrollment-token=${EnrollmentToken}
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 32
Outputs:
  Ec2InstanceId:
    Value: !Ref ElasticAgentEc2Instance
    Description: The EC2 instance ID
  Ec2InstancePublicIp:
    Value: !GetAtt ElasticAgentEc2Instance.PublicIp
    Description: The EC2 instance public IP
