---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates IAM roles needed for multi-account access
Parameters:
  OrganizationalUnitIds:
    Type: CommaDelimitedList
    Description: |
      Comma-separated list of organizational units to deploy the IAM roles to.
      Specify the unique IDs of the organizational units where the roles should be deployed.
      Example: ou-abc123,ou-def456,ou-ghi789
    AllowedPattern: '.+'
Resources:
  CloudbeatRootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: cloudbeat-root
      Description: Role that cloudbeat uses to assume roles in other accounts
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: cloudbeat-root-permissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - organizations:ListAccounts
                Resource: "*"
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: "*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
  CloudbeatRoleStackSet:
    Type: 'AWS::CloudFormation::StackSet'
    Properties:
      StackSetName: cloudbeat-role-stackset
      Description: StackSet for deploying the cloudbeat-securityaudit IAM role to member accounts in the specified organizational units.
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Capabilities:
        - CAPABILITY_NAMED_IAM
      ManagedExecution:
        Active: true
      Parameters:
        - ParameterKey: RootRoleArn
          ParameterValue: !GetAtt CloudbeatRootRole.Arn
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref OrganizationalUnitIds
          Regions:
            - !Ref AWS::Region
      TemplateBody: |
        AWSTemplateFormatVersion: '2010-09-09'
        Description: Creates IAM roles needed for multi-account access
        Parameters:
          RootRoleArn:
            Type: String
        Resources:
          CloudbeatMemberRole:
            Type: 'AWS::IAM::Role'
            Properties:
              RoleName: cloudbeat-securityaudit
              AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Principal:
                      AWS: !Ref RootRoleArn
                    Action:
                      - sts:AssumeRole
              Path: /
              ManagedPolicyArns:
                - arn:aws:iam::aws:policy/SecurityAudit
Outputs:
  CloudbeatRootRoleArn:
    Value: !GetAtt CloudbeatRootRole.Arn
    Description: The cloudbeat IAM role in the management account
