// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.15.0. DO NOT EDIT.

package iam

import (
	context "context"

	serviceiam "github.com/aws/aws-sdk-go-v2/service/iam"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GenerateCredentialReport provides a mock function with given fields: ctx, params, optFns
func (_m *MockClient) GenerateCredentialReport(ctx context.Context, params *serviceiam.GenerateCredentialReportInput, optFns ...func(*serviceiam.Options)) (*serviceiam.GenerateCredentialReportOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *serviceiam.GenerateCredentialReportOutput
	if rf, ok := ret.Get(0).(func(context.Context, *serviceiam.GenerateCredentialReportInput, ...func(*serviceiam.Options)) *serviceiam.GenerateCredentialReportOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceiam.GenerateCredentialReportOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *serviceiam.GenerateCredentialReportInput, ...func(*serviceiam.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GenerateCredentialReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCredentialReport'
type MockClient_GenerateCredentialReport_Call struct {
	*mock.Call
}

// GenerateCredentialReport is a helper method to define mock.On call
//   - ctx context.Context
//   - params *serviceiam.GenerateCredentialReportInput
//   - optFns ...func(*serviceiam.Options)
func (_e *MockClient_Expecter) GenerateCredentialReport(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_GenerateCredentialReport_Call {
	return &MockClient_GenerateCredentialReport_Call{Call: _e.mock.On("GenerateCredentialReport",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_GenerateCredentialReport_Call) Run(run func(ctx context.Context, params *serviceiam.GenerateCredentialReportInput, optFns ...func(*serviceiam.Options))) *MockClient_GenerateCredentialReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*serviceiam.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*serviceiam.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*serviceiam.GenerateCredentialReportInput), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_GenerateCredentialReport_Call) Return(_a0 *serviceiam.GenerateCredentialReportOutput, _a1 error) *MockClient_GenerateCredentialReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetAccessKeyLastUsed provides a mock function with given fields: ctx, params, optFns
func (_m *MockClient) GetAccessKeyLastUsed(ctx context.Context, params *serviceiam.GetAccessKeyLastUsedInput, optFns ...func(*serviceiam.Options)) (*serviceiam.GetAccessKeyLastUsedOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *serviceiam.GetAccessKeyLastUsedOutput
	if rf, ok := ret.Get(0).(func(context.Context, *serviceiam.GetAccessKeyLastUsedInput, ...func(*serviceiam.Options)) *serviceiam.GetAccessKeyLastUsedOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceiam.GetAccessKeyLastUsedOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *serviceiam.GetAccessKeyLastUsedInput, ...func(*serviceiam.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetAccessKeyLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessKeyLastUsed'
type MockClient_GetAccessKeyLastUsed_Call struct {
	*mock.Call
}

// GetAccessKeyLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - params *serviceiam.GetAccessKeyLastUsedInput
//   - optFns ...func(*serviceiam.Options)
func (_e *MockClient_Expecter) GetAccessKeyLastUsed(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_GetAccessKeyLastUsed_Call {
	return &MockClient_GetAccessKeyLastUsed_Call{Call: _e.mock.On("GetAccessKeyLastUsed",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_GetAccessKeyLastUsed_Call) Run(run func(ctx context.Context, params *serviceiam.GetAccessKeyLastUsedInput, optFns ...func(*serviceiam.Options))) *MockClient_GetAccessKeyLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*serviceiam.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*serviceiam.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*serviceiam.GetAccessKeyLastUsedInput), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_GetAccessKeyLastUsed_Call) Return(_a0 *serviceiam.GetAccessKeyLastUsedOutput, _a1 error) *MockClient_GetAccessKeyLastUsed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetAccountPasswordPolicy provides a mock function with given fields: ctx, params, optFns
func (_m *MockClient) GetAccountPasswordPolicy(ctx context.Context, params *serviceiam.GetAccountPasswordPolicyInput, optFns ...func(*serviceiam.Options)) (*serviceiam.GetAccountPasswordPolicyOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *serviceiam.GetAccountPasswordPolicyOutput
	if rf, ok := ret.Get(0).(func(context.Context, *serviceiam.GetAccountPasswordPolicyInput, ...func(*serviceiam.Options)) *serviceiam.GetAccountPasswordPolicyOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceiam.GetAccountPasswordPolicyOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *serviceiam.GetAccountPasswordPolicyInput, ...func(*serviceiam.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetAccountPasswordPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountPasswordPolicy'
type MockClient_GetAccountPasswordPolicy_Call struct {
	*mock.Call
}

// GetAccountPasswordPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - params *serviceiam.GetAccountPasswordPolicyInput
//   - optFns ...func(*serviceiam.Options)
func (_e *MockClient_Expecter) GetAccountPasswordPolicy(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_GetAccountPasswordPolicy_Call {
	return &MockClient_GetAccountPasswordPolicy_Call{Call: _e.mock.On("GetAccountPasswordPolicy",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_GetAccountPasswordPolicy_Call) Run(run func(ctx context.Context, params *serviceiam.GetAccountPasswordPolicyInput, optFns ...func(*serviceiam.Options))) *MockClient_GetAccountPasswordPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*serviceiam.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*serviceiam.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*serviceiam.GetAccountPasswordPolicyInput), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_GetAccountPasswordPolicy_Call) Return(_a0 *serviceiam.GetAccountPasswordPolicyOutput, _a1 error) *MockClient_GetAccountPasswordPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetCredentialReport provides a mock function with given fields: ctx, params, optFns
func (_m *MockClient) GetCredentialReport(ctx context.Context, params *serviceiam.GetCredentialReportInput, optFns ...func(*serviceiam.Options)) (*serviceiam.GetCredentialReportOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *serviceiam.GetCredentialReportOutput
	if rf, ok := ret.Get(0).(func(context.Context, *serviceiam.GetCredentialReportInput, ...func(*serviceiam.Options)) *serviceiam.GetCredentialReportOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceiam.GetCredentialReportOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *serviceiam.GetCredentialReportInput, ...func(*serviceiam.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetCredentialReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentialReport'
type MockClient_GetCredentialReport_Call struct {
	*mock.Call
}

// GetCredentialReport is a helper method to define mock.On call
//   - ctx context.Context
//   - params *serviceiam.GetCredentialReportInput
//   - optFns ...func(*serviceiam.Options)
func (_e *MockClient_Expecter) GetCredentialReport(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_GetCredentialReport_Call {
	return &MockClient_GetCredentialReport_Call{Call: _e.mock.On("GetCredentialReport",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_GetCredentialReport_Call) Run(run func(ctx context.Context, params *serviceiam.GetCredentialReportInput, optFns ...func(*serviceiam.Options))) *MockClient_GetCredentialReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*serviceiam.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*serviceiam.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*serviceiam.GetCredentialReportInput), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_GetCredentialReport_Call) Return(_a0 *serviceiam.GetCredentialReportOutput, _a1 error) *MockClient_GetCredentialReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetRolePolicy provides a mock function with given fields: ctx, params, optFns
func (_m *MockClient) GetRolePolicy(ctx context.Context, params *serviceiam.GetRolePolicyInput, optFns ...func(*serviceiam.Options)) (*serviceiam.GetRolePolicyOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *serviceiam.GetRolePolicyOutput
	if rf, ok := ret.Get(0).(func(context.Context, *serviceiam.GetRolePolicyInput, ...func(*serviceiam.Options)) *serviceiam.GetRolePolicyOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceiam.GetRolePolicyOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *serviceiam.GetRolePolicyInput, ...func(*serviceiam.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetRolePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRolePolicy'
type MockClient_GetRolePolicy_Call struct {
	*mock.Call
}

// GetRolePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - params *serviceiam.GetRolePolicyInput
//   - optFns ...func(*serviceiam.Options)
func (_e *MockClient_Expecter) GetRolePolicy(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_GetRolePolicy_Call {
	return &MockClient_GetRolePolicy_Call{Call: _e.mock.On("GetRolePolicy",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_GetRolePolicy_Call) Run(run func(ctx context.Context, params *serviceiam.GetRolePolicyInput, optFns ...func(*serviceiam.Options))) *MockClient_GetRolePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*serviceiam.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*serviceiam.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*serviceiam.GetRolePolicyInput), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_GetRolePolicy_Call) Return(_a0 *serviceiam.GetRolePolicyOutput, _a1 error) *MockClient_GetRolePolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListAccessKeys provides a mock function with given fields: ctx, params, optFns
func (_m *MockClient) ListAccessKeys(ctx context.Context, params *serviceiam.ListAccessKeysInput, optFns ...func(*serviceiam.Options)) (*serviceiam.ListAccessKeysOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *serviceiam.ListAccessKeysOutput
	if rf, ok := ret.Get(0).(func(context.Context, *serviceiam.ListAccessKeysInput, ...func(*serviceiam.Options)) *serviceiam.ListAccessKeysOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceiam.ListAccessKeysOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *serviceiam.ListAccessKeysInput, ...func(*serviceiam.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListAccessKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccessKeys'
type MockClient_ListAccessKeys_Call struct {
	*mock.Call
}

// ListAccessKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - params *serviceiam.ListAccessKeysInput
//   - optFns ...func(*serviceiam.Options)
func (_e *MockClient_Expecter) ListAccessKeys(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_ListAccessKeys_Call {
	return &MockClient_ListAccessKeys_Call{Call: _e.mock.On("ListAccessKeys",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_ListAccessKeys_Call) Run(run func(ctx context.Context, params *serviceiam.ListAccessKeysInput, optFns ...func(*serviceiam.Options))) *MockClient_ListAccessKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*serviceiam.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*serviceiam.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*serviceiam.ListAccessKeysInput), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_ListAccessKeys_Call) Return(_a0 *serviceiam.ListAccessKeysOutput, _a1 error) *MockClient_ListAccessKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListAttachedRolePolicies provides a mock function with given fields: ctx, params, optFns
func (_m *MockClient) ListAttachedRolePolicies(ctx context.Context, params *serviceiam.ListAttachedRolePoliciesInput, optFns ...func(*serviceiam.Options)) (*serviceiam.ListAttachedRolePoliciesOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *serviceiam.ListAttachedRolePoliciesOutput
	if rf, ok := ret.Get(0).(func(context.Context, *serviceiam.ListAttachedRolePoliciesInput, ...func(*serviceiam.Options)) *serviceiam.ListAttachedRolePoliciesOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceiam.ListAttachedRolePoliciesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *serviceiam.ListAttachedRolePoliciesInput, ...func(*serviceiam.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListAttachedRolePolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAttachedRolePolicies'
type MockClient_ListAttachedRolePolicies_Call struct {
	*mock.Call
}

// ListAttachedRolePolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - params *serviceiam.ListAttachedRolePoliciesInput
//   - optFns ...func(*serviceiam.Options)
func (_e *MockClient_Expecter) ListAttachedRolePolicies(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_ListAttachedRolePolicies_Call {
	return &MockClient_ListAttachedRolePolicies_Call{Call: _e.mock.On("ListAttachedRolePolicies",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_ListAttachedRolePolicies_Call) Run(run func(ctx context.Context, params *serviceiam.ListAttachedRolePoliciesInput, optFns ...func(*serviceiam.Options))) *MockClient_ListAttachedRolePolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*serviceiam.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*serviceiam.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*serviceiam.ListAttachedRolePoliciesInput), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_ListAttachedRolePolicies_Call) Return(_a0 *serviceiam.ListAttachedRolePoliciesOutput, _a1 error) *MockClient_ListAttachedRolePolicies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListMFADevices provides a mock function with given fields: ctx, params, optFns
func (_m *MockClient) ListMFADevices(ctx context.Context, params *serviceiam.ListMFADevicesInput, optFns ...func(*serviceiam.Options)) (*serviceiam.ListMFADevicesOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *serviceiam.ListMFADevicesOutput
	if rf, ok := ret.Get(0).(func(context.Context, *serviceiam.ListMFADevicesInput, ...func(*serviceiam.Options)) *serviceiam.ListMFADevicesOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceiam.ListMFADevicesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *serviceiam.ListMFADevicesInput, ...func(*serviceiam.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListMFADevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMFADevices'
type MockClient_ListMFADevices_Call struct {
	*mock.Call
}

// ListMFADevices is a helper method to define mock.On call
//   - ctx context.Context
//   - params *serviceiam.ListMFADevicesInput
//   - optFns ...func(*serviceiam.Options)
func (_e *MockClient_Expecter) ListMFADevices(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_ListMFADevices_Call {
	return &MockClient_ListMFADevices_Call{Call: _e.mock.On("ListMFADevices",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_ListMFADevices_Call) Run(run func(ctx context.Context, params *serviceiam.ListMFADevicesInput, optFns ...func(*serviceiam.Options))) *MockClient_ListMFADevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*serviceiam.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*serviceiam.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*serviceiam.ListMFADevicesInput), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_ListMFADevices_Call) Return(_a0 *serviceiam.ListMFADevicesOutput, _a1 error) *MockClient_ListMFADevices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, params, optFns
func (_m *MockClient) ListUsers(ctx context.Context, params *serviceiam.ListUsersInput, optFns ...func(*serviceiam.Options)) (*serviceiam.ListUsersOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *serviceiam.ListUsersOutput
	if rf, ok := ret.Get(0).(func(context.Context, *serviceiam.ListUsersInput, ...func(*serviceiam.Options)) *serviceiam.ListUsersOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceiam.ListUsersOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *serviceiam.ListUsersInput, ...func(*serviceiam.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockClient_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - params *serviceiam.ListUsersInput
//   - optFns ...func(*serviceiam.Options)
func (_e *MockClient_Expecter) ListUsers(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_ListUsers_Call {
	return &MockClient_ListUsers_Call{Call: _e.mock.On("ListUsers",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_ListUsers_Call) Run(run func(ctx context.Context, params *serviceiam.ListUsersInput, optFns ...func(*serviceiam.Options))) *MockClient_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*serviceiam.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*serviceiam.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*serviceiam.ListUsersInput), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_ListUsers_Call) Return(_a0 *serviceiam.ListUsersOutput, _a1 error) *MockClient_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewMockClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockClient(t mockConstructorTestingTNewMockClient) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
