// Code generated by mockery v2.10.4. DO NOT EDIT.

package aws

import (
	mock "github.com/stretchr/testify/mock"
)

// MockedAwsCredentialsGetter is an autogenerated mock type for the AwsCredentialsGetter type
type MockedAwsCredentialsGetter struct {
	mock.Mock
}

type MockedAwsCredentialsGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockedAwsCredentialsGetter) EXPECT() *MockedAwsCredentialsGetter_Expecter {
	return &MockedAwsCredentialsGetter_Expecter{mock: &_m.Mock}
}

// GetAwsCredentials provides a mock function with given fields:
func (_m *MockedAwsCredentialsGetter) GetAwsCredentials() FetcherConfig {
	ret := _m.Called()

	var r0 FetcherConfig
	if rf, ok := ret.Get(0).(func() FetcherConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(FetcherConfig)
	}

	return r0
}

// MockedAwsCredentialsGetter_GetAwsCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAwsCredentials'
type MockedAwsCredentialsGetter_GetAwsCredentials_Call struct {
	*mock.Call
}

// GetAwsCredentials is a helper method to define mock.On call
func (_e *MockedAwsCredentialsGetter_Expecter) GetAwsCredentials() *MockedAwsCredentialsGetter_GetAwsCredentials_Call {
	return &MockedAwsCredentialsGetter_GetAwsCredentials_Call{Call: _e.mock.On("GetAwsCredentials")}
}

func (_c *MockedAwsCredentialsGetter_GetAwsCredentials_Call) Run(run func()) *MockedAwsCredentialsGetter_GetAwsCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockedAwsCredentialsGetter_GetAwsCredentials_Call) Return(_a0 FetcherConfig) *MockedAwsCredentialsGetter_GetAwsCredentials_Call {
	_c.Call.Return(_a0)
	return _c
}
