# Deploy a cloudbeat instance per node for cis policy
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudbeat
  namespace: kube-system
  labels:
    k8s-app: cloudbeat
spec:
  selector:
    matchLabels:
      k8s-app: cloudbeat
  template:
    metadata:
      labels:
        k8s-app: cloudbeat
    spec:
      serviceAccountName: cloudbeat
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: cloudbeat
        image: cloudbeat:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_HOST
          value: "host.docker.internal:9200"
        - name: ES_USERNAME
          value: elastic
        - name: ES_PASSWORD
          value: changeme
        - name: KIBANA_HOST
          value: "http://host.docker.internal:5601"
        - name: ELASTIC_CLOUD_ID
          value: none
        - name: ELASTIC_CLOUD_AUTH
          value: none
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        resources:
          # limits:
          #   memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /cloudbeat.yml
          readOnly: true
          subPath: cloudbeat.yml
        - name: proc
          mountPath: /hostfs/proc
          readOnly: true
        - name: etc-kubernetes
          mountPath: /hostfs/etc/kubernetes
        - name: var-lib
          mountPath: /hostfs/var/lib
          readOnly: true
        - name: cgroup
          mountPath: /hostfs/sys/fs/cgroup
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: passwd
          mountPath: /hostfs/etc/passwd
          readOnly: true
        - name: group
          mountPath: /hostfs/etc/group
          readOnly: true
        - name: etcsysmd
          mountPath: /hostfs/etc/systemd
          readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: etc-kubernetes
          hostPath:
            path: /etc/kubernetes
        - name: var-lib
          hostPath:
            path: /var/lib
        - name: passwd
          hostPath:
            path: /etc/passwd
        - name: group
          hostPath:
            path: /etc/group
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log
        - name: etcsysmd
          hostPath:
            path: /etc/systemd
        - name: config
          configMap:
            defaultMode: 0640
            name: cloudbeat-daemonset-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudbeat-daemonset-config
  namespace: kube-system
  labels:
    k8s-app: cloudbeat
data:
  cloudbeat.yml: |-
    cloudbeat:
      # Defines how often an event is sent to the output
      period: 30s
      files: [
          "/hostfs/etc/kubernetes/scheduler.conf",
          "/hostfs/etc/kubernetes/controller-manager.conf",
          "/hostfs/etc/kubernetes/admin.conf",
          "/hostfs/etc/kubernetes/kubelet.conf",
          "/hostfs/etc/kubernetes/manifests/etcd.yaml",
          "/hostfs/etc/kubernetes/manifests/kube-apiserver.yaml",
          "/hostfs/etc/kubernetes/manifests/kube-controller-manager.yaml",
          "/hostfs/etc/kubernetes/manifests/kube-scheduler.yaml",
          "/hostfs/etc/systemd/system/kubelet.service.d/10-kubeadm.conf",
          "/hostfs/var/lib/kubelet/config.yaml",
          "/hostfs/var/lib/etcd",
          "/hostfs/etc/kubernetes/pki"
      ]

    # =================================== Kibana ===================================
    setup.kibana:

      # Kibana Host
      host: "http://host.docker.internal:5601"
    # =============================== Elastic Cloud ================================

    # These settings simplify using Cloudbeat with the Elastic Cloud (https://cloud.elastic.co/).

    # The cloud.id setting overwrites the `output.elasticsearch.hosts` and
    # `setup.kibana.host` options.
    # You can find the `cloud.id` in the Elastic Cloud web UI.
    #cloud.id:

    # The cloud.auth setting overwrites the `output.elasticsearch.username` and
    # `output.elasticsearch.password` settings. The format is `<user>:<pass>`.
    #cloud.auth:

    # ---------------------------- Elasticsearch Output ----------------------------
    output.elasticsearch:
      # Array of hosts to connect to.
      hosts: ${ES_HOST}

      # Protocol - either `http` (default) or `https`.
      #protocol: "https"

      # Authentication credentials - either API key or username/password.
      #api_key: "id:api_key"
      username: ${ES_USERNAME}
      password: ${ES_PASSWORD}

    # ================================= Processors =================================
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~
      - add_docker_metadata: ~

    # Sets log level. The default log level is info.
    # Available log levels are: error, warning, info, debug
    logging.level: debug

    # Enable debug output for selected components. To enable all selectors use ["*"]
    # Other available selectors are "beat", "publisher", "service"
    # Multiple selectors can be chained.
    #logging.selectors: ["publisher"]

    # Send all logging output to stderr. The default is false.
    logging.to_stderr: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudbeat
  namespace: kube-system
  labels:
    k8s-app: cloudbeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudbeat
  labels:
    k8s-app: cloudbeat
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  - services
  verbs: ["get", "list", "watch"]
# Enable this rule only if planing to use Kubernetes keystore
#- apiGroups: [""]
#  resources:
#  - secrets
#  verbs: ["get"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudbeat
  # should be the namespace where cloudbeat is running
  namespace: kube-system
  labels:
    k8s-app: cloudbeat
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudbeat-kubeadm-config
  namespace: kube-system
  labels:
    k8s-app: cloudbeat
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - kubeadm-config
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudbeat
subjects:
- kind: ServiceAccount
  name: cloudbeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cloudbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudbeat
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: cloudbeat
    namespace: kube-system
roleRef:
  kind: Role
  name: cloudbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudbeat-kubeadm-config
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: cloudbeat
    namespace: kube-system
roleRef:
  kind: Role
  name: cloudbeat-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
---
