name: 'Init Integration Test'
description: 'Init integration test'
inputs:
  elk-version:
    description: 'ELK version'
    required: true
  build-cloudbeat:
    description: 'Build cloudbeat'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Build cloudbeat binary
      if: ${{ inputs.build-cloudbeat == 'true' }}
      shell: bash
      run: mage -v build

    - name: Run elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@98431b45a60cbb6ace481778827bc8e11f12fd65 # master
      with:
        stack-version: ${{ inputs.elk-version }}
        security-enabled: false

    - name: Elasticsearch disable dynamic mapping for findings
      shell: bash
      run: ./.ci/scripts/disable_dynamic_mapping.sh
