// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//go:build !release

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package route53

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/route53"
	"github.com/elastic/cloudbeat/internal/resources/providers/awslib"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// ListHostedZones provides a mock function for the type MockClient
func (_mock *MockClient) ListHostedZones(ctx context.Context, params *route53.ListHostedZonesInput, optFns ...func(*route53.Options)) (*route53.ListHostedZonesOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListHostedZones")
	}

	var r0 *route53.ListHostedZonesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *route53.ListHostedZonesInput, ...func(*route53.Options)) (*route53.ListHostedZonesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *route53.ListHostedZonesInput, ...func(*route53.Options)) *route53.ListHostedZonesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*route53.ListHostedZonesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *route53.ListHostedZonesInput, ...func(*route53.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListHostedZones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHostedZones'
type MockClient_ListHostedZones_Call struct {
	*mock.Call
}

// ListHostedZones is a helper method to define mock.On call
//   - ctx context.Context
//   - params *route53.ListHostedZonesInput
//   - optFns ...func(*route53.Options)
func (_e *MockClient_Expecter) ListHostedZones(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_ListHostedZones_Call {
	return &MockClient_ListHostedZones_Call{Call: _e.mock.On("ListHostedZones",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_ListHostedZones_Call) Run(run func(ctx context.Context, params *route53.ListHostedZonesInput, optFns ...func(*route53.Options))) *MockClient_ListHostedZones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *route53.ListHostedZonesInput
		if args[1] != nil {
			arg1 = args[1].(*route53.ListHostedZonesInput)
		}
		var arg2 []func(*route53.Options)
		var variadicArgs []func(*route53.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*route53.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_ListHostedZones_Call) Return(listHostedZonesOutput *route53.ListHostedZonesOutput, err error) *MockClient_ListHostedZones_Call {
	_c.Call.Return(listHostedZonesOutput, err)
	return _c
}

func (_c *MockClient_ListHostedZones_Call) RunAndReturn(run func(ctx context.Context, params *route53.ListHostedZonesInput, optFns ...func(*route53.Options)) (*route53.ListHostedZonesOutput, error)) *MockClient_ListHostedZones_Call {
	_c.Call.Return(run)
	return _c
}

// ListResourceRecordSets provides a mock function for the type MockClient
func (_mock *MockClient) ListResourceRecordSets(ctx context.Context, params *route53.ListResourceRecordSetsInput, optFns ...func(*route53.Options)) (*route53.ListResourceRecordSetsOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListResourceRecordSets")
	}

	var r0 *route53.ListResourceRecordSetsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *route53.ListResourceRecordSetsInput, ...func(*route53.Options)) (*route53.ListResourceRecordSetsOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *route53.ListResourceRecordSetsInput, ...func(*route53.Options)) *route53.ListResourceRecordSetsOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*route53.ListResourceRecordSetsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *route53.ListResourceRecordSetsInput, ...func(*route53.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListResourceRecordSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResourceRecordSets'
type MockClient_ListResourceRecordSets_Call struct {
	*mock.Call
}

// ListResourceRecordSets is a helper method to define mock.On call
//   - ctx context.Context
//   - params *route53.ListResourceRecordSetsInput
//   - optFns ...func(*route53.Options)
func (_e *MockClient_Expecter) ListResourceRecordSets(ctx interface{}, params interface{}, optFns ...interface{}) *MockClient_ListResourceRecordSets_Call {
	return &MockClient_ListResourceRecordSets_Call{Call: _e.mock.On("ListResourceRecordSets",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockClient_ListResourceRecordSets_Call) Run(run func(ctx context.Context, params *route53.ListResourceRecordSetsInput, optFns ...func(*route53.Options))) *MockClient_ListResourceRecordSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *route53.ListResourceRecordSetsInput
		if args[1] != nil {
			arg1 = args[1].(*route53.ListResourceRecordSetsInput)
		}
		var arg2 []func(*route53.Options)
		var variadicArgs []func(*route53.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*route53.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_ListResourceRecordSets_Call) Return(listResourceRecordSetsOutput *route53.ListResourceRecordSetsOutput, err error) *MockClient_ListResourceRecordSets_Call {
	_c.Call.Return(listResourceRecordSetsOutput, err)
	return _c
}

func (_c *MockClient_ListResourceRecordSets_Call) RunAndReturn(run func(ctx context.Context, params *route53.ListResourceRecordSetsInput, optFns ...func(*route53.Options)) (*route53.ListResourceRecordSetsOutput, error)) *MockClient_ListResourceRecordSets_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecordsLister creates a new instance of MockRecordsLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecordsLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecordsLister {
	mock := &MockRecordsLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRecordsLister is an autogenerated mock type for the RecordsLister type
type MockRecordsLister struct {
	mock.Mock
}

type MockRecordsLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecordsLister) EXPECT() *MockRecordsLister_Expecter {
	return &MockRecordsLister_Expecter{mock: &_m.Mock}
}

// ListRecords provides a mock function for the type MockRecordsLister
func (_mock *MockRecordsLister) ListRecords(ctx context.Context) ([]awslib.AwsResource, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRecords")
	}

	var r0 []awslib.AwsResource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]awslib.AwsResource, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []awslib.AwsResource); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]awslib.AwsResource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRecordsLister_ListRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecords'
type MockRecordsLister_ListRecords_Call struct {
	*mock.Call
}

// ListRecords is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRecordsLister_Expecter) ListRecords(ctx interface{}) *MockRecordsLister_ListRecords_Call {
	return &MockRecordsLister_ListRecords_Call{Call: _e.mock.On("ListRecords", ctx)}
}

func (_c *MockRecordsLister_ListRecords_Call) Run(run func(ctx context.Context)) *MockRecordsLister_ListRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecordsLister_ListRecords_Call) Return(awsResources []awslib.AwsResource, err error) *MockRecordsLister_ListRecords_Call {
	_c.Call.Return(awsResources, err)
	return _c
}

func (_c *MockRecordsLister_ListRecords_Call) RunAndReturn(run func(ctx context.Context) ([]awslib.AwsResource, error)) *MockRecordsLister_ListRecords_Call {
	_c.Call.Return(run)
	return _c
}
