// Code generated by mockery v2.10.0. DO NOT EDIT.

package evaluator

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockedEvaluator is an autogenerated mock type for the MockedEvaluator type
type MockedEvaluator struct {
	mock.Mock
}

// Decision provides a mock function with given fields: _a0, _a1
func (_m MockedEvaluator) Decision(_a0 context.Context, _a1 interface{}) (interface{}, error) {
	ret := _m.Called(_a0, _a1)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) interface{}); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Decode provides a mock function with given fields: result
func (_m MockedEvaluator) Decode(result interface{}) ([]Finding, error) {
	ret := _m.Called(result)

	var r0 []Finding
	if rf, ok := ret.Get(0).(func(interface{}) []Finding); ok {
		r0 = rf(result)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Finding)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(result)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Stop provides a mock function with given fields: _a0
func (_m MockedEvaluator) Stop(_a0 context.Context) {
	_m.Called(_a0)
}
