name: 'CNVM CI'
description: 'CNVM integration tests'
inputs:
  elk-version:
    description: 'ELK version'
    required: true
  aws-access-key-id:
    description: 'AWS access key id'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
runs:
  using: composite
  steps:
    - name: Build cloudbeat binary
      shell: bash
      run: mage -v build

    - name: Run elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: ${{ inputs.elk-version }}
        security-enabled: false

    - name: Elasticsearch disable dynamic mapping for findings
      shell: bash
      run: ./.ci/scripts/disable_dynamic_mapping.sh

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Run cloudbeat in background
      env:
        ES_HOST: http://localhost:9200
        ES_USERNAME: elastic
        ES_PASSWORD: changeme
      shell: bash
      run: ./cloudbeat -c deploy/vulnerability/cloudbeat-vuln-mgmt.yml -d '*' &

    - name: Wait for cloudbeat to send some events
      shell: bash
      run: sleep 10

    - name: Check for findings
      working-directory: ./tests
      env:
        USE_K8S: "false"
      shell: bash
      run: |
        poetry run pytest -k "cnvm" --alluredir=./allure/results/ --clean-alluredir

    - name: Stop cloudbeat
      shell: bash
      run: pkill -15 cloudbeat

    - name: Upload test results
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-ci-cnvm
        path: tests/allure/results/

    # - name: Print cloudbeat logs
    #   if: always()
    #   shell: bash
    #   run: |
    #     cat logs/cloudbeat*
    # - name: Upload cloudbeat logs
    #   if: always()
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: cloubeat-logs-ci-cnvm
    #     path: logs/
