env:
  BRANCH: "${BUILDKITE_BRANCH}"
agents:
  provider: "gcp" # needed for running docker commands
  image: "family/platform-ingest-beats-ubuntu-2204"

steps:
  # TODO: this will be removed/changed for 9.0 branch
  - label: ":writing_hand: Conditionally set VERSION_QUALIFIER for main branch"
    if: build.branch == "main"
    env:
      VERSION_QUALIFIER: "alpha1"
    command: "echo 'Setting VERSION_QUALIFIER for branch main'"

  - label: ":package: Package Cloudbeat - Snapshot"
    if: build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9x]+\$/ || build.env("RUN_RELEASE") == "true"
    env:
      WORKFLOW: "snapshot"
    key: "package-snapshot"
    command: "./.buildkite/scripts/package.sh"
    artifact_paths: "build/distributions/*"

  - label: ":rocket: Publishing Snapshot DRA artifacts"
    if: build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9x]+\$/ || build.env("RUN_RELEASE") == "true"
    depends_on: "package-snapshot"
    command: "./.buildkite/scripts/publish.sh"
    env:
      WORKFLOW: "snapshot"

    # Allow building staging from main when VERSION_QUALIFIER is set (allow prerelease testing)
    # TODO remove || build.env('VERSION_QUALIFIER') != null
  - label: ":package: Package Cloudbeat - Staging"
    if: build.branch =~ /^[0-9]+\.[0-9]+\$/ || build.env("RUN_RELEASE") == "true" || build.env('VERSION_QUALIFIER') != null
    env:
      WORKFLOW: "staging"
    key: "package-staging"
    command: "./.buildkite/scripts/package.sh"
    artifact_paths: "build/distributions/*"

  # TODO remove || build.env('VERSION_QUALIFIER') != null
  - label: ":rocket: Publishing Staging DRA artifacts"
    if: build.branch =~ /^[0-9]+\.[0-9]+\$/ || build.env("RUN_RELEASE") == "true" || build.env('VERSION_QUALIFIER') != null
    depends_on: "package-staging"
    command: "./.buildkite/scripts/publish.sh"
    env:
      WORKFLOW: "staging"

  - wait: ~
    continue_on_failure: true

  - label: "Send Slack Notification"
    command: ".buildkite/scripts/notify.sh | buildkite-agent pipeline upload"
