env:
  BRANCH: "${BUILDKITE_BRANCH}"
agents:
  provider: "gcp" # needed for running docker commands

steps:
  - label: ":package: Package Cloudbeat - Snapshot"
    if: build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9]+\$/ || build.env("RUN_RELEASE") == "true"
    env:
      WORKFLOW: "snapshot"
    key: "package-snapshot"
    command: "./.buildkite/scripts/package.sh"
    artifact_paths: "build/distributions/*"

  - label: ":rocket: Publishing Snapshot DRA artifacts"
    if: build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9]+\$/ || build.env("RUN_RELEASE") == "true"
    depends_on: "package-snapshot"
    command: "./.buildkite/scripts/publish.sh"
    env:
      WORKFLOW: "snapshot"

  - label: ":package: Package Cloudbeat - Staging"
    if: build.branch =~ /^[0-9]+\.[0-9]+\$/ || build.env("RUN_RELEASE") == "true"
    env:
      WORKFLOW: "staging"
    key: "package-staging"
    command: "./.buildkite/scripts/package.sh"
    artifact_paths: "build/distributions/*"

  - label: ":rocket: Publishing Staging DRA artifacts"
    if: build.branch =~ /^[0-9]+\.[0-9]+\$/ || build.env("RUN_RELEASE") == "true"
    depends_on: "package-staging"
    command: "./.buildkite/scripts/publish.sh"
    env:
      WORKFLOW: "staging"
