name: "CIS Agentless Integrations Installation"
description: "Deploy CIS Agentless Integrations to Elastic Cloud"
inputs:
  cspm-azure-creds:
    description: "Azure credentials for CSPM agent deployment"
    required: true
    type: string
  cspm-aws-access-key-id:
    description: "AWS Access Key ID for CSPM agentless deployment"
    required: true
    type: string
  cspm-aws-secret-access-key:
    description: "AWS Secret Access Key for CSPM agentless deployment"
    required: true
    type: string
  es-user:
    description: "Elasticsearch user"
    default: "elastic"
    required: false
    type: string
  es-password:
    description: "Elasticsearch password"
    default: "changeme"
    required: false
    type: string
  kibana-url:
    description: "Kibana URL"
    default: "default"
    required: false
    type: string
  serverless-mode:
    required: false
    description: "Set to true if the environment is serverless"
    default: "false"

runs:
  using: composite
  steps:
    - name: Install Agentless integrations
      id: agentless-integrations
      working-directory: tests/integrations_setup
      shell: bash
      env:
        AZURE_CREDENTIALS: ${{ inputs.cspm-azure-creds }}
        AWS_ACCESS_KEY_ID: ${{ inputs.cspm-aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.cspm-aws-secret-access-key }}
        ES_USER: ${{ inputs.es-user }}
        ES_PASSWORD: ${{ inputs.es-password }}
        KIBANA_URL: ${{ inputs.kibana-url }}
        SERVERLESS_MODE: ${{ inputs.serverless-mode }}
      run: |
        poetry run python ./install_agentless_integrations.py
