# $COMMUNITY/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../../base

configMapGenerator:
  - name: cloudbeat-daemonset-config
    behavior: create
    files:
      - cloudbeat.yml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    k8s-app: cloudbeat
