name: "Flaky Test"
description: "Report a flaky test (one that doesn't pass consistently)"
labels: ["flaky-test"]
projects: ["elastic/705"]
body:
  - type: input
    id: test-name
    attributes:
      label: "Test Name"
      description: "Name of the failing test."
    validations:
      required: true

  - type: input
    id: links
    attributes:
      label: "Links"
      description: "Links to failing Github Action and file line"
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: "Branch / PR"
      description: "Git branch or PR the test was seen in."
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: "Notes"
      description: "Additional details about the test, e.g., theory as to failure cause."
    validations:
      required: false

  - type: textarea
    id: stack-trace
    attributes:
      label: "Stack Trace/Logs"
      description: "Paste stack trace or logs here."
      render: shell
    validations:
      required: false
