apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: cloudbeat-daemonset-config
    options:
      disableNameSuffixHash: true
      labels:
        k8s-app: cloudbeat
    namespace: kube-system
    behavior: create
    files:
      - cloudbeat.yml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: cloudbeat
  path: daemonset_patch.yml