// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//go:build !release

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sns

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sns"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// ListSubscriptionsByTopic provides a mock function for the type MockClient
func (_mock *MockClient) ListSubscriptionsByTopic(context1 context.Context, listSubscriptionsByTopicInput *sns.ListSubscriptionsByTopicInput, fns ...func(*sns.Options)) (*sns.ListSubscriptionsByTopicOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, listSubscriptionsByTopicInput, fns)
	} else {
		tmpRet = _mock.Called(context1, listSubscriptionsByTopicInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListSubscriptionsByTopic")
	}

	var r0 *sns.ListSubscriptionsByTopicOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sns.ListSubscriptionsByTopicInput, ...func(*sns.Options)) (*sns.ListSubscriptionsByTopicOutput, error)); ok {
		return returnFunc(context1, listSubscriptionsByTopicInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sns.ListSubscriptionsByTopicInput, ...func(*sns.Options)) *sns.ListSubscriptionsByTopicOutput); ok {
		r0 = returnFunc(context1, listSubscriptionsByTopicInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.ListSubscriptionsByTopicOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sns.ListSubscriptionsByTopicInput, ...func(*sns.Options)) error); ok {
		r1 = returnFunc(context1, listSubscriptionsByTopicInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListSubscriptionsByTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSubscriptionsByTopic'
type MockClient_ListSubscriptionsByTopic_Call struct {
	*mock.Call
}

// ListSubscriptionsByTopic is a helper method to define mock.On call
//   - context1 context.Context
//   - listSubscriptionsByTopicInput *sns.ListSubscriptionsByTopicInput
//   - fns ...func(*sns.Options)
func (_e *MockClient_Expecter) ListSubscriptionsByTopic(context1 interface{}, listSubscriptionsByTopicInput interface{}, fns ...interface{}) *MockClient_ListSubscriptionsByTopic_Call {
	return &MockClient_ListSubscriptionsByTopic_Call{Call: _e.mock.On("ListSubscriptionsByTopic",
		append([]interface{}{context1, listSubscriptionsByTopicInput}, fns...)...)}
}

func (_c *MockClient_ListSubscriptionsByTopic_Call) Run(run func(context1 context.Context, listSubscriptionsByTopicInput *sns.ListSubscriptionsByTopicInput, fns ...func(*sns.Options))) *MockClient_ListSubscriptionsByTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sns.ListSubscriptionsByTopicInput
		if args[1] != nil {
			arg1 = args[1].(*sns.ListSubscriptionsByTopicInput)
		}
		var arg2 []func(*sns.Options)
		var variadicArgs []func(*sns.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sns.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_ListSubscriptionsByTopic_Call) Return(listSubscriptionsByTopicOutput *sns.ListSubscriptionsByTopicOutput, err error) *MockClient_ListSubscriptionsByTopic_Call {
	_c.Call.Return(listSubscriptionsByTopicOutput, err)
	return _c
}

func (_c *MockClient_ListSubscriptionsByTopic_Call) RunAndReturn(run func(context1 context.Context, listSubscriptionsByTopicInput *sns.ListSubscriptionsByTopicInput, fns ...func(*sns.Options)) (*sns.ListSubscriptionsByTopicOutput, error)) *MockClient_ListSubscriptionsByTopic_Call {
	_c.Call.Return(run)
	return _c
}

// ListTopics provides a mock function for the type MockClient
func (_mock *MockClient) ListTopics(context1 context.Context, listTopicsInput *sns.ListTopicsInput, fns ...func(*sns.Options)) (*sns.ListTopicsOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, listTopicsInput, fns)
	} else {
		tmpRet = _mock.Called(context1, listTopicsInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListTopics")
	}

	var r0 *sns.ListTopicsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sns.ListTopicsInput, ...func(*sns.Options)) (*sns.ListTopicsOutput, error)); ok {
		return returnFunc(context1, listTopicsInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sns.ListTopicsInput, ...func(*sns.Options)) *sns.ListTopicsOutput); ok {
		r0 = returnFunc(context1, listTopicsInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.ListTopicsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sns.ListTopicsInput, ...func(*sns.Options)) error); ok {
		r1 = returnFunc(context1, listTopicsInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListTopics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTopics'
type MockClient_ListTopics_Call struct {
	*mock.Call
}

// ListTopics is a helper method to define mock.On call
//   - context1 context.Context
//   - listTopicsInput *sns.ListTopicsInput
//   - fns ...func(*sns.Options)
func (_e *MockClient_Expecter) ListTopics(context1 interface{}, listTopicsInput interface{}, fns ...interface{}) *MockClient_ListTopics_Call {
	return &MockClient_ListTopics_Call{Call: _e.mock.On("ListTopics",
		append([]interface{}{context1, listTopicsInput}, fns...)...)}
}

func (_c *MockClient_ListTopics_Call) Run(run func(context1 context.Context, listTopicsInput *sns.ListTopicsInput, fns ...func(*sns.Options))) *MockClient_ListTopics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sns.ListTopicsInput
		if args[1] != nil {
			arg1 = args[1].(*sns.ListTopicsInput)
		}
		var arg2 []func(*sns.Options)
		var variadicArgs []func(*sns.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sns.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_ListTopics_Call) Return(listTopicsOutput *sns.ListTopicsOutput, err error) *MockClient_ListTopics_Call {
	_c.Call.Return(listTopicsOutput, err)
	return _c
}

func (_c *MockClient_ListTopics_Call) RunAndReturn(run func(context1 context.Context, listTopicsInput *sns.ListTopicsInput, fns ...func(*sns.Options)) (*sns.ListTopicsOutput, error)) *MockClient_ListTopics_Call {
	_c.Call.Return(run)
	return _c
}
