// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.53.2. DO NOT EDIT.

package inventory

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockResourceGraphProviderAPI is an autogenerated mock type for the ResourceGraphProviderAPI type
type MockResourceGraphProviderAPI struct {
	mock.Mock
}

type MockResourceGraphProviderAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceGraphProviderAPI) EXPECT() *MockResourceGraphProviderAPI_Expecter {
	return &MockResourceGraphProviderAPI_Expecter{mock: &_m.Mock}
}

// ListAllAssetTypesByName provides a mock function with given fields: ctx, assetsGroup, assets
func (_m *MockResourceGraphProviderAPI) ListAllAssetTypesByName(ctx context.Context, assetsGroup string, assets []string) ([]AzureAsset, error) {
	ret := _m.Called(ctx, assetsGroup, assets)

	if len(ret) == 0 {
		panic("no return value specified for ListAllAssetTypesByName")
	}

	var r0 []AzureAsset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) ([]AzureAsset, error)); ok {
		return rf(ctx, assetsGroup, assets)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) []AzureAsset); ok {
		r0 = rf(ctx, assetsGroup, assets)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AzureAsset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, assetsGroup, assets)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceGraphProviderAPI_ListAllAssetTypesByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllAssetTypesByName'
type MockResourceGraphProviderAPI_ListAllAssetTypesByName_Call struct {
	*mock.Call
}

// ListAllAssetTypesByName is a helper method to define mock.On call
//   - ctx context.Context
//   - assetsGroup string
//   - assets []string
func (_e *MockResourceGraphProviderAPI_Expecter) ListAllAssetTypesByName(ctx interface{}, assetsGroup interface{}, assets interface{}) *MockResourceGraphProviderAPI_ListAllAssetTypesByName_Call {
	return &MockResourceGraphProviderAPI_ListAllAssetTypesByName_Call{Call: _e.mock.On("ListAllAssetTypesByName", ctx, assetsGroup, assets)}
}

func (_c *MockResourceGraphProviderAPI_ListAllAssetTypesByName_Call) Run(run func(ctx context.Context, assetsGroup string, assets []string)) *MockResourceGraphProviderAPI_ListAllAssetTypesByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockResourceGraphProviderAPI_ListAllAssetTypesByName_Call) Return(_a0 []AzureAsset, _a1 error) *MockResourceGraphProviderAPI_ListAllAssetTypesByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceGraphProviderAPI_ListAllAssetTypesByName_Call) RunAndReturn(run func(context.Context, string, []string) ([]AzureAsset, error)) *MockResourceGraphProviderAPI_ListAllAssetTypesByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResourceGraphProviderAPI creates a new instance of MockResourceGraphProviderAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceGraphProviderAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceGraphProviderAPI {
	mock := &MockResourceGraphProviderAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
