// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.53.2. DO NOT EDIT.

package inventory

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSecurityContactsProviderAPI is an autogenerated mock type for the SecurityContactsProviderAPI type
type MockSecurityContactsProviderAPI struct {
	mock.Mock
}

type MockSecurityContactsProviderAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecurityContactsProviderAPI) EXPECT() *MockSecurityContactsProviderAPI_Expecter {
	return &MockSecurityContactsProviderAPI_Expecter{mock: &_m.Mock}
}

// ListAutoProvisioningSettings provides a mock function with given fields: ctx, subscriptionID
func (_m *MockSecurityContactsProviderAPI) ListAutoProvisioningSettings(ctx context.Context, subscriptionID string) ([]AzureAsset, error) {
	ret := _m.Called(ctx, subscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for ListAutoProvisioningSettings")
	}

	var r0 []AzureAsset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]AzureAsset, error)); ok {
		return rf(ctx, subscriptionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []AzureAsset); ok {
		r0 = rf(ctx, subscriptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AzureAsset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, subscriptionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecurityContactsProviderAPI_ListAutoProvisioningSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAutoProvisioningSettings'
type MockSecurityContactsProviderAPI_ListAutoProvisioningSettings_Call struct {
	*mock.Call
}

// ListAutoProvisioningSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionID string
func (_e *MockSecurityContactsProviderAPI_Expecter) ListAutoProvisioningSettings(ctx interface{}, subscriptionID interface{}) *MockSecurityContactsProviderAPI_ListAutoProvisioningSettings_Call {
	return &MockSecurityContactsProviderAPI_ListAutoProvisioningSettings_Call{Call: _e.mock.On("ListAutoProvisioningSettings", ctx, subscriptionID)}
}

func (_c *MockSecurityContactsProviderAPI_ListAutoProvisioningSettings_Call) Run(run func(ctx context.Context, subscriptionID string)) *MockSecurityContactsProviderAPI_ListAutoProvisioningSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSecurityContactsProviderAPI_ListAutoProvisioningSettings_Call) Return(_a0 []AzureAsset, _a1 error) *MockSecurityContactsProviderAPI_ListAutoProvisioningSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecurityContactsProviderAPI_ListAutoProvisioningSettings_Call) RunAndReturn(run func(context.Context, string) ([]AzureAsset, error)) *MockSecurityContactsProviderAPI_ListAutoProvisioningSettings_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecurityContacts provides a mock function with given fields: ctx, subscriptionID
func (_m *MockSecurityContactsProviderAPI) ListSecurityContacts(ctx context.Context, subscriptionID string) ([]AzureAsset, error) {
	ret := _m.Called(ctx, subscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for ListSecurityContacts")
	}

	var r0 []AzureAsset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]AzureAsset, error)); ok {
		return rf(ctx, subscriptionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []AzureAsset); ok {
		r0 = rf(ctx, subscriptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AzureAsset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, subscriptionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecurityContactsProviderAPI_ListSecurityContacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecurityContacts'
type MockSecurityContactsProviderAPI_ListSecurityContacts_Call struct {
	*mock.Call
}

// ListSecurityContacts is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionID string
func (_e *MockSecurityContactsProviderAPI_Expecter) ListSecurityContacts(ctx interface{}, subscriptionID interface{}) *MockSecurityContactsProviderAPI_ListSecurityContacts_Call {
	return &MockSecurityContactsProviderAPI_ListSecurityContacts_Call{Call: _e.mock.On("ListSecurityContacts", ctx, subscriptionID)}
}

func (_c *MockSecurityContactsProviderAPI_ListSecurityContacts_Call) Run(run func(ctx context.Context, subscriptionID string)) *MockSecurityContactsProviderAPI_ListSecurityContacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSecurityContactsProviderAPI_ListSecurityContacts_Call) Return(_a0 []AzureAsset, _a1 error) *MockSecurityContactsProviderAPI_ListSecurityContacts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecurityContactsProviderAPI_ListSecurityContacts_Call) RunAndReturn(run func(context.Context, string) ([]AzureAsset, error)) *MockSecurityContactsProviderAPI_ListSecurityContacts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecurityContactsProviderAPI creates a new instance of MockSecurityContactsProviderAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecurityContactsProviderAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecurityContactsProviderAPI {
	mock := &MockSecurityContactsProviderAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
