name: "Stack Asset Inventory Dependency"
description: "Verify stack support for asset inventory"
inputs:
  stack_version:
    description: "Stack version"
    required: true

runs:
  using: composite
  steps:
    - name: Check stack version for asset inventory support
      id: check-asset-inventory-version
      outputs: 
        asset_inventory_supported: ${{ steps.check-asset-inventory-version.outputs.asset_inventory_supported }}
      shell: bash
      run: |
        MIN_VERSION="8.16.0"
        if [[ "$(echo -e "$MIN_VERSION\n${{ inputs.stack_version }}" | sort -V | head -n 1)" == "$MIN_VERSION" ]]; then
          echo "Stack version meets the requirement: ${{ inputs.stack_version }} >= $MIN_VERSION."
          echo "asset_inventory_supported=true" >> $GITHUB_ENV
        else
          echo "Stack version is below the requirement: ${{ inputs.stack_version }} < $MIN_VERSION."
          echo "asset_inventory_supported=false" >> $GITHUB_ENV
        fi
