// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.37.1. DO NOT EDIT.

package cloudfront

import (
	context "context"

	awslib "github.com/elastic/cloudbeat/internal/resources/providers/awslib"

	mock "github.com/stretchr/testify/mock"
)

// MockDescriptor is an autogenerated mock type for the Descriptor type
type MockDescriptor struct {
	mock.Mock
}

type MockDescriptor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDescriptor) EXPECT() *MockDescriptor_Expecter {
	return &MockDescriptor_Expecter{mock: &_m.Mock}
}

// DescribeDistributions provides a mock function with given fields: ctx
func (_m *MockDescriptor) DescribeDistributions(ctx context.Context) ([]awslib.AwsResource, error) {
	ret := _m.Called(ctx)

	var r0 []awslib.AwsResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]awslib.AwsResource, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []awslib.AwsResource); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]awslib.AwsResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDescriptor_DescribeDistributions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeDistributions'
type MockDescriptor_DescribeDistributions_Call struct {
	*mock.Call
}

// DescribeDistributions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDescriptor_Expecter) DescribeDistributions(ctx interface{}) *MockDescriptor_DescribeDistributions_Call {
	return &MockDescriptor_DescribeDistributions_Call{Call: _e.mock.On("DescribeDistributions", ctx)}
}

func (_c *MockDescriptor_DescribeDistributions_Call) Run(run func(ctx context.Context)) *MockDescriptor_DescribeDistributions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDescriptor_DescribeDistributions_Call) Return(_a0 []awslib.AwsResource, _a1 error) *MockDescriptor_DescribeDistributions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDescriptor_DescribeDistributions_Call) RunAndReturn(run func(context.Context) ([]awslib.AwsResource, error)) *MockDescriptor_DescribeDistributions_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeKeyValueStores provides a mock function with given fields: ctx
func (_m *MockDescriptor) DescribeKeyValueStores(ctx context.Context) ([]awslib.AwsResource, error) {
	ret := _m.Called(ctx)

	var r0 []awslib.AwsResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]awslib.AwsResource, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []awslib.AwsResource); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]awslib.AwsResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDescriptor_DescribeKeyValueStores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeKeyValueStores'
type MockDescriptor_DescribeKeyValueStores_Call struct {
	*mock.Call
}

// DescribeKeyValueStores is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDescriptor_Expecter) DescribeKeyValueStores(ctx interface{}) *MockDescriptor_DescribeKeyValueStores_Call {
	return &MockDescriptor_DescribeKeyValueStores_Call{Call: _e.mock.On("DescribeKeyValueStores", ctx)}
}

func (_c *MockDescriptor_DescribeKeyValueStores_Call) Run(run func(ctx context.Context)) *MockDescriptor_DescribeKeyValueStores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDescriptor_DescribeKeyValueStores_Call) Return(_a0 []awslib.AwsResource, _a1 error) *MockDescriptor_DescribeKeyValueStores_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDescriptor_DescribeKeyValueStores_Call) RunAndReturn(run func(context.Context) ([]awslib.AwsResource, error)) *MockDescriptor_DescribeKeyValueStores_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDescriptor creates a new instance of MockDescriptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDescriptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDescriptor {
	mock := &MockDescriptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
