---
# GAP: https://github.com/elastic/cloudbeat/issues/162
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: elastic-agent-cluster-leader
  namespace: kube-system
spec:
  holderIdentity: cloudbeat-leader
  leaseDurationSeconds: 15
  renewTime: "1992-04-26T00:00:00.000000Z"