// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.15.0. DO NOT EDIT.

package logs

import (
	context "context"

	types "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs/types"
	mock "github.com/stretchr/testify/mock"
)

// MockCloudwatchLogs is an autogenerated mock type for the CloudwatchLogs type
type MockCloudwatchLogs struct {
	mock.Mock
}

// DescribeMetricFilters provides a mock function with given fields: ctx, logGroup
func (_m *MockCloudwatchLogs) DescribeMetricFilters(ctx context.Context, logGroup string) ([]types.MetricFilter, error) {
	ret := _m.Called(ctx, logGroup)

	var r0 []types.MetricFilter
	if rf, ok := ret.Get(0).(func(context.Context, string) []types.MetricFilter); ok {
		r0 = rf(ctx, logGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.MetricFilter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, logGroup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockCloudwatchLogs interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCloudwatchLogs creates a new instance of MockCloudwatchLogs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCloudwatchLogs(t mockConstructorTestingTNewMockCloudwatchLogs) *MockCloudwatchLogs {
	mock := &MockCloudwatchLogs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
