// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package inventory

import mock "github.com/stretchr/testify/mock"

// MockAssetEnricher is an autogenerated mock type for the AssetEnricher type
type MockAssetEnricher struct {
	mock.Mock
}

type MockAssetEnricher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssetEnricher) EXPECT() *MockAssetEnricher_Expecter {
	return &MockAssetEnricher_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: asset
func (_m *MockAssetEnricher) Execute(asset *AssetEvent) {
	_m.Called(asset)
}

// MockAssetEnricher_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAssetEnricher_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - asset *AssetEvent
func (_e *MockAssetEnricher_Expecter) Execute(asset interface{}) *MockAssetEnricher_Execute_Call {
	return &MockAssetEnricher_Execute_Call{Call: _e.mock.On("Execute", asset)}
}

func (_c *MockAssetEnricher_Execute_Call) Run(run func(asset *AssetEvent)) *MockAssetEnricher_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*AssetEvent))
	})
	return _c
}

func (_c *MockAssetEnricher_Execute_Call) Return() *MockAssetEnricher_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAssetEnricher_Execute_Call) RunAndReturn(run func(*AssetEvent)) *MockAssetEnricher_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockAssetEnricher creates a new instance of MockAssetEnricher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssetEnricher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssetEnricher {
	mock := &MockAssetEnricher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
