kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-test-proc-conf2
nodes:
- role: control-plane
  image: kindest/node:v1.23.12
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "test-conf-1=pass"
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    scheduler:
      extraArgs:
        profiling: "false"
        bind-address: "127.0.0.1"
    controllerManager:
      extraArgs:
        profiling: "false"
        feature-gates: "RotateKubeletServerCertificate=true"
  extraMounts:
  - hostPath: ./tests/allure/results
    containerPath: /tmp/data
  extraPortMappings:
  - containerPort: 9200
    hostPort: 9200
    listenAddress: "127.0.0.1"
  - containerPort: 5601
    hostPort: 5601
    listenAddress: "127.0.0.1"
- role: worker
  image: kindest/node:v1.23.12
  extraMounts:
  - hostPath: ./tests/allure/results
    containerPath: /tmp/data
