# a cluster with 3 control-plane nodes and 3 workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-mono
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./tests/allure/results
    containerPath: /tmp/data

# Todo Enable EphemeralContainers on kind config for debug