// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//go:build !release

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package awsfetcher

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/iam/types"
	"github.com/elastic/cloudbeat/internal/resources/providers/awslib/ec2"
	mock "github.com/stretchr/testify/mock"
)

// newMockEc2InstancesProvider creates a new instance of mockEc2InstancesProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEc2InstancesProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEc2InstancesProvider {
	mock := &mockEc2InstancesProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockEc2InstancesProvider is an autogenerated mock type for the ec2InstancesProvider type
type mockEc2InstancesProvider struct {
	mock.Mock
}

type mockEc2InstancesProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockEc2InstancesProvider) EXPECT() *mockEc2InstancesProvider_Expecter {
	return &mockEc2InstancesProvider_Expecter{mock: &_m.Mock}
}

// DescribeInstances provides a mock function for the type mockEc2InstancesProvider
func (_mock *mockEc2InstancesProvider) DescribeInstances(ctx context.Context) ([]*ec2.Ec2Instance, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DescribeInstances")
	}

	var r0 []*ec2.Ec2Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*ec2.Ec2Instance, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*ec2.Ec2Instance); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ec2.Ec2Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockEc2InstancesProvider_DescribeInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeInstances'
type mockEc2InstancesProvider_DescribeInstances_Call struct {
	*mock.Call
}

// DescribeInstances is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockEc2InstancesProvider_Expecter) DescribeInstances(ctx interface{}) *mockEc2InstancesProvider_DescribeInstances_Call {
	return &mockEc2InstancesProvider_DescribeInstances_Call{Call: _e.mock.On("DescribeInstances", ctx)}
}

func (_c *mockEc2InstancesProvider_DescribeInstances_Call) Run(run func(ctx context.Context)) *mockEc2InstancesProvider_DescribeInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockEc2InstancesProvider_DescribeInstances_Call) Return(ec2Instances []*ec2.Ec2Instance, err error) *mockEc2InstancesProvider_DescribeInstances_Call {
	_c.Call.Return(ec2Instances, err)
	return _c
}

func (_c *mockEc2InstancesProvider_DescribeInstances_Call) RunAndReturn(run func(ctx context.Context) ([]*ec2.Ec2Instance, error)) *mockEc2InstancesProvider_DescribeInstances_Call {
	_c.Call.Return(run)
	return _c
}

// newMockInstanceProfileResolver creates a new instance of mockInstanceProfileResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockInstanceProfileResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockInstanceProfileResolver {
	mock := &mockInstanceProfileResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockInstanceProfileResolver is an autogenerated mock type for the instanceProfileResolver type
type mockInstanceProfileResolver struct {
	mock.Mock
}

type mockInstanceProfileResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockInstanceProfileResolver) EXPECT() *mockInstanceProfileResolver_Expecter {
	return &mockInstanceProfileResolver_Expecter{mock: &_m.Mock}
}

// GetInstanceProfile provides a mock function for the type mockInstanceProfileResolver
func (_mock *mockInstanceProfileResolver) GetInstanceProfile(ctx context.Context, instanceProfileName string) (*types.InstanceProfile, error) {
	ret := _mock.Called(ctx, instanceProfileName)

	if len(ret) == 0 {
		panic("no return value specified for GetInstanceProfile")
	}

	var r0 *types.InstanceProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.InstanceProfile, error)); ok {
		return returnFunc(ctx, instanceProfileName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.InstanceProfile); ok {
		r0 = returnFunc(ctx, instanceProfileName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.InstanceProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, instanceProfileName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockInstanceProfileResolver_GetInstanceProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstanceProfile'
type mockInstanceProfileResolver_GetInstanceProfile_Call struct {
	*mock.Call
}

// GetInstanceProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceProfileName string
func (_e *mockInstanceProfileResolver_Expecter) GetInstanceProfile(ctx interface{}, instanceProfileName interface{}) *mockInstanceProfileResolver_GetInstanceProfile_Call {
	return &mockInstanceProfileResolver_GetInstanceProfile_Call{Call: _e.mock.On("GetInstanceProfile", ctx, instanceProfileName)}
}

func (_c *mockInstanceProfileResolver_GetInstanceProfile_Call) Run(run func(ctx context.Context, instanceProfileName string)) *mockInstanceProfileResolver_GetInstanceProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockInstanceProfileResolver_GetInstanceProfile_Call) Return(instanceProfile *types.InstanceProfile, err error) *mockInstanceProfileResolver_GetInstanceProfile_Call {
	_c.Call.Return(instanceProfile, err)
	return _c
}

func (_c *mockInstanceProfileResolver_GetInstanceProfile_Call) RunAndReturn(run func(ctx context.Context, instanceProfileName string) (*types.InstanceProfile, error)) *mockInstanceProfileResolver_GetInstanceProfile_Call {
	_c.Call.Return(run)
	return _c
}
