// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.37.1. DO NOT EDIT.

package awslib

import (
	context "context"

	aws "github.com/aws/aws-sdk-go-v2/aws"
	clog "github.com/elastic/cloudbeat/internal/infra/clog"

	mock "github.com/stretchr/testify/mock"
)

// MockCrossRegionFactory is an autogenerated mock type for the CrossRegionFactory type
type MockCrossRegionFactory[T interface{}] struct {
	mock.Mock
}

type MockCrossRegionFactory_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockCrossRegionFactory[T]) EXPECT() *MockCrossRegionFactory_Expecter[T] {
	return &MockCrossRegionFactory_Expecter[T]{mock: &_m.Mock}
}

// NewMultiRegionClients provides a mock function with given fields: ctx, selector, cfg, factory, log
func (_m *MockCrossRegionFactory[T]) NewMultiRegionClients(ctx context.Context, selector RegionsSelector, cfg aws.Config, factory func(aws.Config) T, log *clog.Logger) CrossRegionFetcher[T] {
	ret := _m.Called(ctx, selector, cfg, factory, log)

	var r0 CrossRegionFetcher[T]
	if rf, ok := ret.Get(0).(func(context.Context, RegionsSelector, aws.Config, func(aws.Config) T, *clog.Logger) CrossRegionFetcher[T]); ok {
		r0 = rf(ctx, selector, cfg, factory, log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CrossRegionFetcher[T])
		}
	}

	return r0
}

// MockCrossRegionFactory_NewMultiRegionClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewMultiRegionClients'
type MockCrossRegionFactory_NewMultiRegionClients_Call[T interface{}] struct {
	*mock.Call
}

// NewMultiRegionClients is a helper method to define mock.On call
//   - ctx context.Context
//   - selector RegionsSelector
//   - cfg aws.Config
//   - factory func(aws.Config) T
//   - log *clog.Logger
func (_e *MockCrossRegionFactory_Expecter[T]) NewMultiRegionClients(ctx interface{}, selector interface{}, cfg interface{}, factory interface{}, log interface{}) *MockCrossRegionFactory_NewMultiRegionClients_Call[T] {
	return &MockCrossRegionFactory_NewMultiRegionClients_Call[T]{Call: _e.mock.On("NewMultiRegionClients", ctx, selector, cfg, factory, log)}
}

func (_c *MockCrossRegionFactory_NewMultiRegionClients_Call[T]) Run(run func(ctx context.Context, selector RegionsSelector, cfg aws.Config, factory func(aws.Config) T, log *clog.Logger)) *MockCrossRegionFactory_NewMultiRegionClients_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(RegionsSelector), args[2].(aws.Config), args[3].(func(aws.Config) T), args[4].(*clog.Logger))
	})
	return _c
}

func (_c *MockCrossRegionFactory_NewMultiRegionClients_Call[T]) Return(_a0 CrossRegionFetcher[T]) *MockCrossRegionFactory_NewMultiRegionClients_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCrossRegionFactory_NewMultiRegionClients_Call[T]) RunAndReturn(run func(context.Context, RegionsSelector, aws.Config, func(aws.Config) T, *clog.Logger) CrossRegionFetcher[T]) *MockCrossRegionFactory_NewMultiRegionClients_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockCrossRegionFactory creates a new instance of MockCrossRegionFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCrossRegionFactory[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCrossRegionFactory[T] {
	mock := &MockCrossRegionFactory[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
