// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.37.1. DO NOT EDIT.

package lambda

import (
	context "context"

	awslib "github.com/elastic/cloudbeat/internal/resources/providers/awslib"

	mock "github.com/stretchr/testify/mock"
)

// MockLambda is an autogenerated mock type for the Lambda type
type MockLambda struct {
	mock.Mock
}

type MockLambda_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLambda) EXPECT() *MockLambda_Expecter {
	return &MockLambda_Expecter{mock: &_m.Mock}
}

// ListFunctions provides a mock function with given fields: _a0
func (_m *MockLambda) ListFunctions(_a0 context.Context) ([]awslib.AwsResource, error) {
	ret := _m.Called(_a0)

	var r0 []awslib.AwsResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]awslib.AwsResource, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []awslib.AwsResource); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]awslib.AwsResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLambda_ListFunctions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFunctions'
type MockLambda_ListFunctions_Call struct {
	*mock.Call
}

// ListFunctions is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockLambda_Expecter) ListFunctions(_a0 interface{}) *MockLambda_ListFunctions_Call {
	return &MockLambda_ListFunctions_Call{Call: _e.mock.On("ListFunctions", _a0)}
}

func (_c *MockLambda_ListFunctions_Call) Run(run func(_a0 context.Context)) *MockLambda_ListFunctions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLambda_ListFunctions_Call) Return(_a0 []awslib.AwsResource, _a1 error) *MockLambda_ListFunctions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLambda_ListFunctions_Call) RunAndReturn(run func(context.Context) ([]awslib.AwsResource, error)) *MockLambda_ListFunctions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLambda creates a new instance of MockLambda. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLambda(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLambda {
	mock := &MockLambda{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
