// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.15.0. DO NOT EDIT.

package sns

import (
	context "context"

	types "github.com/aws/aws-sdk-go-v2/service/sns/types"
	mock "github.com/stretchr/testify/mock"
)

// MockSNS is an autogenerated mock type for the SNS type
type MockSNS struct {
	mock.Mock
}

// ListSubscriptionsByTopic provides a mock function with given fields: ctx, topic
func (_m *MockSNS) ListSubscriptionsByTopic(ctx context.Context, topic string) ([]types.Subscription, error) {
	ret := _m.Called(ctx, topic)

	var r0 []types.Subscription
	if rf, ok := ret.Get(0).(func(context.Context, string) []types.Subscription); ok {
		r0 = rf(ctx, topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Subscription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, topic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockSNS interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSNS creates a new instance of MockSNS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSNS(t mockConstructorTestingTNewMockSNS) *MockSNS {
	mock := &MockSNS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
