name: Build

on:
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'
    types: [opened, synchronize, reopened]

env:
  CONTAINER_SUFFIX: ${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # This actions also handles the caching of go dependencies
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - run: go version

      - name: Init Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV

      - name: build cloudbeat binary
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: build

      - name: build opa bundle
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: BuildOpaBundle

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Build dependencies
#        if: ${{ !env.ACT }} # skip caching if running on ACT
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.workflow }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build cloudbeat-docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: cloudbeat:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          outputs: type=docker,dest=/tmp/cloudbeat-${{ env.CONTAINER_SUFFIX }}.tar

      - name: Build elastic-agent
        run: |
          make build_elastic_agent_docker_image

      - name: Build pytest-docker
        uses: docker/build-push-action@v3
        with:
          context: ./tests/.
          push: false
          tags: cloudbeat-test:latest
          cache-from: type=local,mode=max,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          outputs: type=docker,dest=/tmp/pytest-${{ env.CONTAINER_SUFFIX }}.tar

      - name: Cache docker images
#        if: ${{ !env.ACT }} # skip caching if running on ACT
        uses: actions/cache@v3
        with:
          path: /tmp/*.tar
          key: ${{ runner.os }}-dockers-cache-${{ env.CONTAINER_SUFFIX }}

      - name: Move cache
#        if: ${{ !env.ACT }} # skip caching if running on ACT
        run: |
          ./.ci/scripts/gh-cache.sh
        shell: bash
