name: Lint

on:
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Lint:
    # for more information see .pre-commit-config.yaml
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Init Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV

      - name: Python lints
        run: |
          git ls-files -- '*.py' | xargs pre-commit run --file
        shell: bash

      - name: Go lints
        run: |
          git ls-files -- '*.go' | xargs pre-commit run --file
        shell: bash
