name: local workflow

on:
  # Ability to execute on demand
  workflow_dispatch:
    inputs:
      cleanup-env:
        description: "Boolean: Cleanup resources after provision"
        default: false

jobs:
  Cleanup:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Cleanup Environment
        if: github.event.inputs.cleanup-env == 'true'
        run: |
          echo 'env destroyed'
