name: Packaging

on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: 1.17.2
  DEV: true
  SNAPSHOT: true
  PLATFORMS: linux/amd64
  GOPATH: /home/runner/go

jobs:
  packag_beat:
    name: Package Cloudbeat
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        types: [ tar.gz, docker ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Mage
        run: |
          git clone https://github.com/magefile/mage
          cd mage
          go run bootstrap.go
          mage -version

      - name: Packaging
        run: |
          mage -v package
        env:
          TYPES: ${{ matrix.types }}