name: CI

on:
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+"
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  init-hermit:
    name: Init Hermit Tools
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Hermit Environment
        uses: ./.github/actions/hermit

  ci-azure:
    needs: [ init-hermit ]
    name: Integrations Tests CIS Azure
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Hermit Environment
        uses: ./.github/actions/hermit

      - name: Build cloudbeat binary
        shell: bash
        run: mage build

      - name: Run Azure integration tests
        uses: ./.github/actions/azure-ci
        with:
          elk-version: ${{ env.ELK_VERSION }}
          azure-client-id: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
          azure-tenant-id: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
          azure-client-secret: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
