name: Allure Report

on:
  workflow_run:
    workflows: ["K8s Functional Tests"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}

permissions:
  checks: write
  # needed unless run with comment_mode: off
  pull-requests: write
  # required by download step to access artifacts API
  actions: read

jobs:
  publish_results:
    timeout-minutes: 15
    name: Publish Results
    runs-on: ubuntu-20.04
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
      - name: Download allure report artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success

      - name: Download and Extract Artifacts
        run: |
          ls -R

      - name: Publish allure report
        if: always()
        uses: andrcuns/allure-publish-action@v2.2.2
        with:
          storageType: s3
          resultsGlob: "tests/allure/results/*"
          updatePr: comment
          summary: total
          copyLatest: true
          bucket: csp-allure-reports
          prefix: allure_reports/cloudbeat/prs/${{ env.PR_NUMBER }}
          ignoreMissingResults: true

      - name: Output to Job Summary
        id: report
        run: |
          echo "### Run Summary :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "[Report](http://csp-allure-reports.s3.amazonaws.com/allure_reports/cloudbeat/prs/${{ env.PR_NUMBER }}/index.html)" >> $GITHUB_STEP_SUMMARY
          jq '.[0].data' tests/allure/results/allure-report/history/history-trend.json -c
          OUTPUT=$(jq '.[0].data' tests/allure/results/allure-report/history/history-trend.json -c | npx tablemark-cli -)
          OUTPUT="${OUTPUT//'Failed'/'\![](https://placehold.co/7x7/fc593e/fc593e.png) Failed'}"
          OUTPUT="${OUTPUT//'Broken'/'\![](https://placehold.co/7x7/ffd050/ffd050.png) Broken'}"
          OUTPUT="${OUTPUT//'Skipped'/'\![](https://placehold.co/7x7/aaaaaa/aaaaaa.png) Skipped'}"
          OUTPUT="${OUTPUT//'Passed'/'\![](https://placehold.co/7x7/97cc64/97cc64.png) Passed'}"
          OUTPUT="${OUTPUT//'Unknown'/'\![](https://placehold.co/7x7/d35ebd/d35ebd.png) Unknown'}"
          OUTPUT="${OUTPUT//'%'/'%25'}​【7,6 m】"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "result=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Comment test success result
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Test Results
          number: ${{ env.PR_NUMBER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ### Cloudbeat CI :robot:
            Test ${{ github.sha }} ended successfully.
            ${{ steps.report.outputs.result }}
            [Report](http://csp-allure-reports.s3.amazonaws.com/allure_reports/cloudbeat/prs/${{ env.PR_NUMBER }}/index.html)
