name: Update rules status

on:
  pull_request:
    branches:
      - main

jobs:
  update_and_commit:
    name: Update and Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      # possibly modifies README.md and RULES.md
      - name: Update rule status
        run: poetry run python dev/update_rule_status.py

      - name: Check for modified files
        id: check_files
        run: |
          if [[ -n "$(git diff --name-only)" ]]; then
            echo "Modified files found."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No modified files found."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      # Commit changes if there are any
      - name: Commit changes
        if: steps.check_files.outputs.has_changes == 'true'
        run: |
          git config --local user.name 'Elastic Machine'
          git config --local user.email 'elasticmachine@users.noreply.github.com'
          git add README.md RULES.md
          git commit -m "Update rules markdown files"
          git push origin HEAD:${{ github.head_ref }}
