name: Sync CIS Rule Templates

on:
  push:
    branches:
      - main
    paths:
      - "security-policies/bundle/compliance/**/rules/**/data.yaml"

env:
  GITHUB_TOKEN: ${{ secrets.CLOUDSEC_MACHINE_TOKEN }}

jobs:
  Sync-Templates:
    name: Sync CIS Rule Templates
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout Integrations repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.CLOUDSEC_MACHINE_TOKEN }}
          repository: elastic/integrations
          path: integrations

      - name: Checkout Cloudbeat repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.CLOUDSEC_MACHINE_TOKEN }}
          path: cloudbeat

      - name: Hermit Environment
        uses: ./.github/actions/hermit
        with:
          init-tools: 'true'
          free-disk: 'true'

      - name: Sync CIS Rules with integrations repo
        working-directory: cloudbeat
        run: scripts/sync_rule_templates.sh
