name: Test Runner
run-name: Test E2E Flow by @${{ github.actor }}

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+"
      - "8.x"
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 2 * * *' # every day at 02:00

jobs:
  run-version:
    strategy:
      fail-fast: false
      # TODO: To enable later
      # max-parallel: 1
      matrix:
        include:
          - type: ech
            region: gcp-us-west2
            serverless: false
            branch: main
          - type: ech
            region: gcp-us-west2
            serverless: false
            branch: 8.x
          - type: serverless
            region: aws-us-east-1
            serverless: true
            branch: main
    name: Run ${{ matrix.type }} on ${{ matrix.branch }} branch
    uses: ./.github/workflows/test-e2e-flow.yml
    secrets: inherit
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      branch: ${{ matrix.branch }}
      deployment-type: ${{ matrix.type }}
      region: ${{ matrix.region }}
      serverless: ${{ matrix.serverless }}
