name: Test OPA Coverage

on:
  push:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./security-policies
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Hermit Environment
        uses: ./.github/actions/hermit
        with:
          init-tools: "true"
          free-disk: "true"

      - name: OPA test coverage
        run: |
          coverage="$(opa test ./bundle -c | jq '.coverage' | cut -d'.' -f1)%"
          echo "COVERAGE=$coverage" >> "$GITHUB_ENV"

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@28b0fa8bdeb46170ac397105ece0c1fe58f68910 # v1.9.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a7160df46e48dff45b24096de9302d38
          filename: csp-security-policies_coverage.json
          label: coverage
          message: ${{ (env.COVERAGE) }}
          namedLogo: Elastic
          color: green
          logoColor: lightblue
