name: Temporary workflow

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+"
jobs:
  explore:
    name: Init
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Hermit Environment
        uses: ./.github/actions/hermit
        with:
          init-tools: 'false'
          free-disk: 'false'
      - name: local hermit folder
        run: |
          ls -lah ./.hermit/
      - name: pkg hermit folder
        run: |
          ls -lah ~/.cache/hermit/pkg/
      - name: python
        run: |
          hermit install
          ls -lah /home/runner/.cache/hermit/pkg/
