// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.15.0. DO NOT EDIT.

package dataprovider

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEnvironmentCommonDataProvider is an autogenerated mock type for the EnvironmentCommonDataProvider type
type MockEnvironmentCommonDataProvider struct {
	mock.Mock
}

type MockEnvironmentCommonDataProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnvironmentCommonDataProvider) EXPECT() *MockEnvironmentCommonDataProvider_Expecter {
	return &MockEnvironmentCommonDataProvider_Expecter{mock: &_m.Mock}
}

// FetchData provides a mock function with given fields: _a0
func (_m *MockEnvironmentCommonDataProvider) FetchData(_a0 context.Context) (CommonData, error) {
	ret := _m.Called(_a0)

	var r0 CommonData
	if rf, ok := ret.Get(0).(func(context.Context) CommonData); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CommonData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnvironmentCommonDataProvider_FetchData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchData'
type MockEnvironmentCommonDataProvider_FetchData_Call struct {
	*mock.Call
}

// FetchData is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockEnvironmentCommonDataProvider_Expecter) FetchData(_a0 interface{}) *MockEnvironmentCommonDataProvider_FetchData_Call {
	return &MockEnvironmentCommonDataProvider_FetchData_Call{Call: _e.mock.On("FetchData", _a0)}
}

func (_c *MockEnvironmentCommonDataProvider_FetchData_Call) Run(run func(_a0 context.Context)) *MockEnvironmentCommonDataProvider_FetchData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEnvironmentCommonDataProvider_FetchData_Call) Return(_a0 CommonData, _a1 error) *MockEnvironmentCommonDataProvider_FetchData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewMockEnvironmentCommonDataProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEnvironmentCommonDataProvider creates a new instance of MockEnvironmentCommonDataProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEnvironmentCommonDataProvider(t mockConstructorTestingTNewMockEnvironmentCommonDataProvider) *MockEnvironmentCommonDataProvider {
	mock := &MockEnvironmentCommonDataProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
